local L                         = Scorpio("SEquipment")._Locale("enUS")
if not L then return end

L["default"]                = "default"
L["mainscale"]              = "Panel size"
L["showlevel"]              = "Display Level"
L["showequipmentname"]      = "Equip name"
L["showenchantgem"]         = "Enchant Gem"
L["showstatsicon"]          = "Stats icon"
L["showstatsframe"]         = "Stats"
L["criticoncolor"]          = "CritIcon"
L["hasteiconcolor"]         = "HasteIcon"
L["masteryiconcolor"]       = "MasteryIcon"
L["versaiconcolor"]         = "VersailityIcon"
L["levelfontcolor"]         = "Level Font"
L["levelbackcolor"]         = "Level Back"
L["statsfontcolor"]         = "Stats Font"
L["unitinfobackcolor"]      = "Main Back"
L["unitinfobordercolor"]    = "Main Border"
L["levelfontsize"]          = "EquipLevelSize"
L["namefontsize"]           = "EquipNameSize"
L["statsiconfontsize"]      = "Stats Icon Size"
L["statsfontsize"]          = "Stats Size"
L["location"]               = " Panel Point"

L["crit"]                   = "C"
L["haste"]                  = "H"
L["mastery"]                = "M"
L["versa"]                  = "V"