local L                         = Scorpio("SEquipment")._Locale("zhCN")
if not L then return end

L["default"]                = "默认"
L["mainscale"]              = "面板大小"
L["showlevel"]              = "显示等级"
L["showequipmentname"]      = "显示装备名称"
L["showenchantgem"]         = "显示附魔宝石"
L["showstatsicon"]          = "显示属性图标"
L["showstatsframe"]         = "显示属性统计"
L["criticoncolor"]          = "爆击图标颜色"
L["hasteiconcolor"]         = "急速图标颜色"
L["masteryiconcolor"]       = "精通图标颜色"
L["versaiconcolor"]         = "全能图标颜色"
L["levelfontcolor"]         = "等级字体颜色"
L["levelbackcolor"]         = "等级背景颜色"
L["statsfontcolor"]         = "属性字体颜色"
L["unitinfobackcolor"]      = "主面板背景颜色"
L["unitinfobordercolor"]    = "主面板边框颜色"
L["levelfontsize"]          = "装备等级大小"
L["namefontsize"]           = "装备名称大小"
L["statsiconfontsize"]      = "属性图标大小"
L["statsfontsize"]          = "属性统计大小"
L["location"]               = "主界面定位"

L["crit"]                   = "爆"
L["haste"]                  = "急"
L["mastery"]                = "精"
L["versa"]                  = "全"

L["showpaperdoll"]          = "人物面板信息"
L["showbag"]                = "包裹信息"
L["showbank"]               = "银行信息"
L["showtooltiplevel"]       = "鼠标提示等级"