local L                         = Scorpio("SEquipment")._Locale("zhTW")
if not L then return end

L["default"]                = "預設"
L["mainscale"]              = "面板大小"
L["showlevel"]              = "顯示等級"
L["showequipmentname"]      = "顯示裝備名稱"
L["showenchantgem"]         = "顯示附魔寶石"
L["showstatsicon"]          = "顯示屬性圖示"
L["showstatsframe"]         = "顯示屬性統計"
L["criticoncolor"]          = "爆擊圖示顏色"
L["hasteiconcolor"]         = "急速圖示顏色"
L["masteryiconcolor"]       = "精通圖示顏色"
L["versaiconcolor"]         = "全能圖示顏色"
L["levelfontcolor"]         = "等級字體顏色"
L["levelbackcolor"]         = "等級背景顏色"
L["statsfontcolor"]         = "屬性字體顏色"
L["unitinfobackcolor"]      = "主面板背景顏色"
L["unitinfobordercolor"]    = "主面板邊框顏色"
L["levelfontsize"]          = "裝備等級大小"
L["namefontsize"]           = "裝備名稱大小"
L["statsiconfontsize"]      = "屬性圖示大小"
L["statsfontsize"]          = "屬性統計大小"
L["location"]               = "主介面定位"

L["crit"]                   = "致"
L["haste"]                  = "速"
L["mastery"]                = "精"
L["versa"]                  = "臨"

L["showpaperdoll"]          = "人物面板資訊"
L["showbag"]                = "包裹資訊"
L["showbank"]               = "銀行資訊"